### ISSUE TITLE
problem in visualize

### ISSUE THREAD

**Issue by masato296132** [HKUST-Aerial-Robotics/SIMPL#13]
Thanks for your great work.When I tried to run sh scripts/simpl_av1_vis.sh,there shows a bug:torch has no gradient.Then I turn 

> vel = torch.gradient(reg, dim=-2)[0] / 0.1 to vel = torch.diff(reg, dim=-2)[0] / 0.1
But torch.cuda.synchronize() has a problem RuntimeError: CUDA error: device-side assert triggered.
Is there any way to solve this problem?

And I notice in function draw_once,eval_out is not  used.Could you please tell me the data format of post_out, data and eval_out?Thanks a lot.

**Comment by masato296132** [comment]
Sorry, I found that my handling method changed the dimension, the problem has been solved.Thank you so much for the excellent visual code.

**Comment by penglo** [comment]
> Thanks for your great work.When I tried to run sh scripts/simpl_av1_vis.sh,there shows a bug:torch has no gradient.Then I turn
> 
> > vel = torch.gradient(reg, dim=-2)[0] / 0.1 to vel = torch.diff(reg, dim=-2)[0] / 0.1
> > But torch.cuda.synchronize() has a problem RuntimeError: CUDA error: device-side assert triggered.
> > Is there any way to solve this problem?
> 
> And I notice in function draw_once,eval_out is not used.Could you please tell me the data format of post_out, data and eval_out?Thanks a lot.

Here's the translation of your message into English:

Hello, I also modified the model following the author's method, but I encountered a problem during visualization: the weights are not matching. I see you have modified the model and visualized it as well. I would like to consult with you if it's convenient. Thank you very much. If possible, could you please leave your email address, or you can contact me directly via email when it's convenient for you. Thank you very much. My email is lipl23@mails.jlu.edu.cn.
你好，我也是结合作者的方法进行了修改模型，但是在可视化的过程中，遇到了问题，加载权重不匹配的问题，看您也是同样修改了模型，并进行了可视化，想请教一下您，不知道您是否方便，万分感谢，如果可以的话，可否留下您的邮箱，或者在您方便的时候您可以直接使用邮箱联系我，万分感谢，我的邮箱是lipl23@ mails.jlu.edu.cn
